- hosts: all
  become: yes
  tasks:
  - name: pull changes made to nix-configs
    shell: 
      chdir=/etc/nixos 
      git pull https://theycallmemac:92ccd6e58768864c0e7cc1d54a7cfbcb1f44c0e9@github.com/theycallmemac/nix-configs.git master
  - name: dry run redeploy NixOS
    shell:
      source ~/.bashrc && nixos-rebuild dry-run
  - name: redeploy NixOS
    shell:
      source ~/.bashrc && nixos-rebuild switch
